#!/usr/bin/env python3
"""
Regenerate the LightNotebook launcher icon.

The mark is a ruled notebook: a page, a margin rule down the left, three lines of
writing. White line art on black, matching the icon language of the sibling Light
Phone III tools.

Geometry is defined once, in the 108x108 adaptive-icon canvas, and emitted twice — as
Android vector paths and as raster fallbacks. Everything sits inside the 18..90 safe
zone so no launcher mask can clip it.

    python3 scripts/generate_icon.py

Needs Pillow. Rewrites app/src/main/res/{drawable,mipmap-*}.
"""

from __future__ import annotations

import os

from PIL import Image, ImageDraw

RES = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res")

CANVAS = 108
SAFE = (18, 90)

STROKE = 3.5
RULE_STROKE = 3.0

# The page.
PAGE = (28.0, 20.0, 86.0, 88.0)  # left, top, right, bottom (centrelines)
# The margin rule, a little in from the spine.
MARGIN_X = 40.0
# Three lines of writing, stopping short of the right edge like real handwriting.
RULES = ((48.0, 42.0, 80.0), (48.0, 56.0, 80.0), (48.0, 70.0, 72.0))


def check_safe_zone() -> None:
    lo, hi = SAFE
    edge = STROKE / 2
    left, top, right, bottom = PAGE
    extents = [
        (left - edge, top - edge),
        (right + edge, bottom + edge),
        (MARGIN_X, top),
    ]
    for x0, _y, x1 in RULES:
        extents.append((x0 - RULE_STROKE / 2, _y))
        extents.append((x1 + RULE_STROKE / 2, _y))
    for x, y in extents:
        assert lo <= x <= hi and lo <= y <= hi, f"({x}, {y}) escapes the safe zone"


def write_vectors() -> None:
    background = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Pure black. On the Light Phone III's panel these pixels are simply off. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{CANVAS}dp"
    android:height="{CANVAS}dp"
    android:viewportWidth="{CANVAS}"
    android:viewportHeight="{CANVAS}">
    <path
        android:fillColor="#000000"
        android:pathData="M0,0h{CANVAS}v{CANVAS}h-{CANVAS}z" />
</vector>
"""

    def stroked(path: str, width: float) -> str:
        return f"""    <path
        android:pathData="{path}"
        android:strokeColor="#FFFFFF"
        android:strokeWidth="{width:g}"
        android:fillColor="#00000000"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />"""

    left, top, right, bottom = PAGE
    page = (
        f"M {left:g},{top:g} L {right:g},{top:g} L {right:g},{bottom:g} "
        f"L {left:g},{bottom:g} Z"
    )
    margin = f"M {MARGIN_X:g},{top:g} L {MARGIN_X:g},{bottom:g}"
    rules = "\n".join(
        stroked(f"M {x0:g},{y:g} L {x1:g},{y:g}", RULE_STROKE) for x0, y, x1 in RULES
    )

    foreground = f"""<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by scripts/generate_icon.py — edit the geometry there, not here.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{CANVAS}dp"
    android:height="{CANVAS}dp"
    android:viewportWidth="{CANVAS}"
    android:viewportHeight="{CANVAS}">
{stroked(page, STROKE)}
{stroked(margin, RULE_STROKE)}
{rules}
</vector>
"""

    adaptive = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
"""

    os.makedirs(os.path.join(RES, "drawable"), exist_ok=True)
    os.makedirs(os.path.join(RES, "mipmap-anydpi-v26"), exist_ok=True)
    with open(os.path.join(RES, "drawable", "ic_launcher_background.xml"), "w") as f:
        f.write(background)
    with open(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"), "w") as f:
        f.write(foreground)
    for name in ("ic_launcher", "ic_launcher_round"):
        with open(os.path.join(RES, "mipmap-anydpi-v26", f"{name}.xml"), "w") as f:
            f.write(adaptive)


DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
SUPERSAMPLE = 8


def render(px: int, circular: bool) -> Image.Image:
    s = SUPERSAMPLE
    img = Image.new("RGBA", (CANVAS * s, CANVAS * s), (0, 0, 0, 255))
    d = ImageDraw.Draw(img)
    white = (255, 255, 255, 255)

    left, top, right, bottom = PAGE
    d.rectangle(
        [left * s, top * s, right * s, bottom * s],
        outline=white,
        width=int(STROKE * s),
    )
    d.line(
        [(MARGIN_X * s, top * s), (MARGIN_X * s, bottom * s)],
        fill=white,
        width=int(RULE_STROKE * s),
    )
    for x0, y, x1 in RULES:
        d.line([(x0 * s, y * s), (x1 * s, y * s)], fill=white, width=int(RULE_STROKE * s))

    # Crop to the 72x72 the launcher actually shows, so the legacy raster matches what
    # the adaptive icon looks like under a mask.
    lo, hi = SAFE
    out = img.crop((lo * s, lo * s, hi * s, hi * s)).resize((px, px), Image.LANCZOS)

    if circular:
        mask = Image.new("L", (px * 4, px * 4), 0)
        ImageDraw.Draw(mask).ellipse([0, 0, px * 4 - 1, px * 4 - 1], fill=255)
        mask = mask.resize((px, px), Image.LANCZOS)
        base = Image.new("RGBA", (px, px), (0, 0, 0, 0))
        base.paste(out, (0, 0), mask)
        out = base
    return out


def write_rasters() -> None:
    for dpi, px in DENSITIES.items():
        folder = os.path.join(RES, f"mipmap-{dpi}")
        os.makedirs(folder, exist_ok=True)
        render(px, False).save(os.path.join(folder, "ic_launcher.png"))
        render(px, True).save(os.path.join(folder, "ic_launcher_round.png"))


if __name__ == "__main__":
    check_safe_zone()
    write_vectors()
    write_rasters()
    print("icon regenerated in", os.path.normpath(RES))
